"""BW-2.3 immutable native catalog snapshots and atomic pointer."""

import sqlalchemy as sa
from alembic import op

revision = "0006_native_catalog"
down_revision = "0005_broker_auth"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catalog_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("broker_account_id", sa.Uuid(), nullable=False),
        sa.Column("provider_id", sa.String(length=48), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["broker_account_id"],
            ["broker_accounts.id"],
            name=op.f("fk_catalog_snapshots_broker_account_id_broker_accounts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_catalog_snapshots")),
        sa.UniqueConstraint(
            "broker_account_id", "fingerprint", name=op.f("uq_catalog_snapshots_broker_account_id")
        ),
    )
    op.create_index(
        op.f("ix_catalog_snapshots_broker_account_id"),
        "catalog_snapshots",
        ["broker_account_id"],
        unique=False,
    )
    op.create_table(
        "catalog_instruments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("native_id", sa.String(length=64), nullable=False),
        sa.Column("exchange_id", sa.String(length=64), nullable=True),
        sa.Column("symbol", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=True),
        sa.Column("exchange", sa.String(length=32), nullable=False),
        sa.Column("segment", sa.String(length=32), nullable=False),
        sa.Column("instrument_type", sa.String(length=32), nullable=False),
        sa.Column("expiry", sa.Date(), nullable=True),
        sa.Column("strike", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("derivative_kind", sa.String(length=3), nullable=True),
        sa.Column("lot_size", sa.Integer(), nullable=False),
        sa.Column("tick_size", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("canonical_id", sa.Uuid(), nullable=True),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["catalog_snapshots.id"],
            name=op.f("fk_catalog_instruments_snapshot_id_catalog_snapshots"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_catalog_instruments")),
        sa.UniqueConstraint("snapshot_id", "exchange", "symbol", name="uq_catalog_exchange_symbol"),
        sa.UniqueConstraint("snapshot_id", "native_id", name="uq_catalog_native_id"),
    )
    op.create_index(
        "ix_catalog_derivative",
        "catalog_instruments",
        ["snapshot_id", "segment", "expiry", "strike", "derivative_kind"],
        unique=False,
    )
    op.create_index("ix_catalog_name", "catalog_instruments", ["snapshot_id", "name"], unique=False)
    op.create_index(
        "ix_catalog_search",
        "catalog_instruments",
        ["snapshot_id", "exchange", "segment", "symbol"],
        unique=False,
    )
    op.create_table(
        "catalog_pointers",
        sa.Column("broker_account_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("refresh_id", sa.Uuid(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_code", sa.String(length=32), nullable=True),
        sa.Column("total_rows", sa.Integer(), nullable=False),
        sa.Column("accepted_rows", sa.Integer(), nullable=False),
        sa.Column("rejected_rows", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["broker_account_id"],
            ["broker_accounts.id"],
            name=op.f("fk_catalog_pointers_broker_account_id_broker_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["catalog_snapshots.id"],
            name=op.f("fk_catalog_pointers_snapshot_id_catalog_snapshots"),
        ),
        sa.PrimaryKeyConstraint("broker_account_id", name=op.f("pk_catalog_pointers")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("catalog_pointers")
    op.drop_index("ix_catalog_search", table_name="catalog_instruments")
    op.drop_index("ix_catalog_name", table_name="catalog_instruments")
    op.drop_index("ix_catalog_derivative", table_name="catalog_instruments")
    op.drop_table("catalog_instruments")
    op.drop_index(op.f("ix_catalog_snapshots_broker_account_id"), table_name="catalog_snapshots")
    op.drop_table("catalog_snapshots")
    # ### end Alembic commands ###
